In [1]:
import os
import pandas as pd

In [2]:
csv_names = os.listdir()  # get names of all files under this directory

In [3]:
csv_names = list(filter(lambda s: '.csv' in s and '2021' in s, csv_names))  # filter out csv files for 2021

In [5]:
# devide names w.r.p to their months
DF = []  # stores the dataframe derived from the csv files
for name in csv_names:
    month = name[:2]
    date = name[3: 5]
    year = '2021'
    df = pd.read_csv(name)
    df['month'] = month
    df['date'] = date
    df['year'] = year
    DF.append(df)

In [6]:
covid_dataset = pd.concat(DF)  # concate (union) all dataframes

In [10]:
covid_dataset.to_csv('daily_covid-19_cases_in_the_us_in_2021.csv')

In [8]:
covid_dataset

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,...,Total_Test_Results,People_Hospitalized,Case_Fatality_Ratio,UID,ISO3,Testing_Rate,Hospitalization_Rate,month,date,year
0,Alabama,US,2021-01-02 05:30:44,32.3182,-86.9023,365747,4872,202137.0,158738.0,1.0,...,3275341.0,NaN,1.332068,84000001.0,USA,66800.273700,NaN,01,01,2021
1,Alaska,US,2021-01-02 05:30:44,61.3707,-152.4044,47019,206,7165.0,39648.0,2.0,...,1275750.0,NaN,0.438121,84000002.0,USA,174391.185778,NaN,01,01,2021
2,American Samoa,US,2021-01-02 05:30:44,-14.2710,-170.1320,0,0,NaN,NaN,60.0,...,2140.0,NaN,NaN,16.0,ASM,3846.084722,NaN,01,01,2021
3,Arizona,US,2021-01-02 05:30:44,33.7298,-111.4312,530267,9015,76934.0,444318.0,4.0,...,5155330.0,NaN,1.700087,84000004.0,USA,39551.860582,NaN,01,01,2021
4,Arkansas,US,2021-01-02 05:30:44,34.9697,-92.3731,229442,3711,199247.0,26484.0,5.0,...,2051488.0,NaN,1.617402,84000005.0,USA,67979.497674,NaN,01,01,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53,Virginia,US,2022-01-01 04:32:44,37.7693,-78.1700,1118518,15587,NaN,NaN,51.0,...,11179014.0,NaN,1.393540,84000051.0,USA,130970.524464,NaN,12,31,2021
54,Washington,US,2022-01-01 04:32:44,47.4009,-121.4905,849075,9853,NaN,NaN,53.0,...,9958651.0,NaN,1.160439,84000053.0,USA,130778.607132,NaN,12,31,2021
55,West Virginia,US,2022-01-01 04:32:44,38.4912,-80.9545,328162,5336,NaN,NaN,54.0,...,4938024.0,NaN,1.626026,84000054.0,USA,275536.772374,NaN,12,31,2021
56,Wisconsin,US,2022-01-01 04:32:44,44.2685,-89.6165,1120663,11173,NaN,NaN,55.0,...,13306669.0,NaN,0.996999,84000055.0,USA,228541.345424,NaN,12,31,2021
57,Wyoming,US,2022-01-01 04:32:44,42.7560,-107.3025,115638,1526,NaN,NaN,56.0,...,1202206.0,NaN,1.319635,84000056.0,USA,207721.348610,NaN,12,31,2021