In [1]:
import os
import pandas as pd

In [2]:
df = pd.read_csv('Daily_Covod19_US.csv')

In [3]:
df

,OID_,Field1,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,...,Total_Test_Results,People_Hospitalized,Case_Fatality_Ratio,UID,ISO3,Testing_Rate,Hospitalization_Rate,month,date,year
0,1,0,Alabama,US,1/2/2021 5:30:44,32.3182,-86.9023,365747,4872,202137.0,...,3275341.0,NaN,1.332068,84000001.0,USA,66800.273700,NaN,1,1,2021
1,2,1,Alaska,US,1/2/2021 5:30:44,61.3707,-152.4044,47019,206,7165.0,...,1275750.0,NaN,0.438121,84000002.0,USA,174391.185778,NaN,1,1,2021
2,3,2,American Samoa,US,1/2/2021 5:30:44,-14.2710,-170.1320,0,0,NaN,...,2140.0,NaN,NaN,16.0,ASM,3846.084722,NaN,1,1,2021
3,4,3,Arizona,US,1/2/2021 5:30:44,33.7298,-111.4312,530267,9015,76934.0,...,5155330.0,NaN,1.700087,84000004.0,USA,39551.860582,NaN,1,1,2021
4,5,4,Arkansas,US,1/2/2021 5:30:44,34.9697,-92.3731,229442,3711,199247.0,...,2051488.0,NaN,1.617402,84000005.0,USA,67979.497674,NaN,1,1,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21165,21166,53,Virginia,US,1/1/2022 4:32:44,37.7693,-78.1700,1118518,15587,NaN,...,11179014.0,NaN,1.393540,84000051.0,USA,130970.524464,NaN,12,31,2021
21166,21167,54,Washington,US,1/1/2022 4:32:44,47.4009,-121.4905,849075,9853,NaN,...,9958651.0,NaN,1.160439,84000053.0,USA,130778.607132,NaN,12,31,2021
21167,21168,55,West Virginia,US,1/1/2022 4:32:44,38.4912,-80.9545,328162,5336,NaN,...,4938024.0,NaN,1.626026,84000054.0,USA,275536.772374,NaN,12,31,2021
21168,21169,56,Wisconsin,US,1/1/2022 4:32:44,44.2685,-89.6165,1120663,11173,NaN,...,13306669.0,NaN,0.996999,84000055.0,USA,228541.345424,NaN,12,31,2021
21169,21170,57,Wyoming,US,1/1/2022 4:32:44,42.7560,-107.3025,115638,1526,NaN,...,1202206.0,NaN,1.319635,84000056.0,USA,207721.348610,NaN,12,31,2021

In [4]:
states = set(df['Province_State'])

In [5]:
max_date = {1: 31, 2: 28, 3: 31, 4: 30, 5: 31, 6: 30, 7: 31, 8: 31, 9: 30, 10: 31, 11: 30, 12: 31}

In [6]:
Rows = []
for state in states:
    for month in range(1, 11):

        row_in_df_1 = df.loc[df['Province_State'] == state].loc[df['month'] == month].loc[df['date'] == 1]
        row_in_df_31 = df.loc[df['Province_State'] == state].loc[df['month'] == month].loc[df['date'] == max_date[month]]
        
        if row_in_df_31.empty or row_in_df_1.empty:
            continue
            
        Confirmed_overall = (row_in_df_31['Confirmed'].reset_index()['Confirmed'][0] + row_in_df_1['Confirmed'].reset_index()['Confirmed'][0]) / 2
        
        Test_overall = (row_in_df_31['Total_Test_Results'].reset_index()['Total_Test_Results'][0] + row_in_df_1['Total_Test_Results'].reset_index()['Total_Test_Results'][0]) / 2
        
        Increased_Confirmed = row_in_df_31['Confirmed'].reset_index()['Confirmed'][0] - row_in_df_1['Confirmed'].reset_index()['Confirmed'][0]       
        
            
        Increased_Deaths = row_in_df_31['Deaths'].reset_index()['Deaths'][0] - row_in_df_1['Deaths'].reset_index()['Deaths'][0]
          
            
        Increased_Recovered = row_in_df_31['Recovered'].reset_index()['Recovered'][0] - row_in_df_1['Recovered'].reset_index()['Recovered'][0]
                       
        
            
        Total_test_in_the_month = row_in_df_31['Total_Test_Results'].reset_index()['Total_Test_Results'][0] - row_in_df_1['Total_Test_Results'].reset_index()['Total_Test_Results'][0]
        
        
        
        
        Rows.append((state, month, Increased_Confirmed, Increased_Deaths, Increased_Recovered, Total_test_in_the_month, Confirmed_overall, Test_overall))

In [7]:
monthly_data = pd.DataFrame(data = Rows, columns = ['State','month', 'Increased_Confirmed', 'Increased_Deaths', 'Increased_Recovered', 'Total_test_in_the_month', 'Confirmed_overall', 'Test_overall'])

In [8]:
monthly_data.to_csv('monthly_covid_increase_data_by_state_2021.csv')